### ISSUE TITLE
Error: tls handshake eof

### ISSUE THREAD

**Issue by 86maid** [rustls/tokio-rustls#37]
Why did this error occur and how can we fix it?

**Comment by cpu** [comment]
Hi there,

In general you'll need to provide more information in order to get the best help. Things like what crate versions you're using, what server you're connecting to when you observe the error, and sample code that shows how you're using the crate.

However in this case I think the explanation is present in the Rustls manual's section on unexpected EOF: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
