### ISSUE TITLE
Infinite loop on `Stream::poll_shutdown()`

### ISSUE THREAD

**Issue by hatoo** [rustls/tokio-rustls#92]
https://github.com/rustls/tokio-rustls/blob/66fb0ae98fbc9e71d5aa855d45e88ca8d53f95f3/src/common/mod.rs#L330-L334

`self.write_io(cx)` in the snippet may returns Ok(0) and causing an infinite loop.

I've faced this issue in my project.
I've failed to minimize codes that trigger this issue but please let me know if you want to see codes.

**Comment by quininer** [comment]
The `write_io` returns `Ok(0)` There are two possibilities:

1. There is no data to be written in session. this is not possible because we have checked `.wants_write()`.
2. The underlying IO stream returns `0` instead of pending, This means that you are using a bad IO stream implement.

**Comment by ctz** [comment]
Sounds like we should convert `Ok(0)` from `write` to `ErrorKind::WriteZero` and have it fail the whole connection.

**Comment by quininer** [comment]
This does surprise me a bit, this is not the behavior of posix `write` or `send`. it looks like std once changed its description, but was reverted. https://github.com/rust-lang/rust/pull/114897

I'd willing to be compatible with this anyway, because there's no harm in it. but i still think IO stream should return an error instead of 0, whether it's BrokenPipe, ConnectionReset or WouldBlock.
